### ISSUE TITLE
Default password for unlock screen?

### ISSUE THREAD

**Issue by ghost** [kibojoe/build-iso#2]
What the hell is default password for unlock screen?

* http://forum.kibojoe.org/viewtopic.php?f=3&p=58#p58

I make LiveUSB and boot from it. Then left
 PC and when I back to it screen was locked (automaticaly).

I try find default password in the docs, but its not described

* https://sourceforge.net/projects/kibojoe/files/Orientation%20Guide/User_Orientation_Guide-17.04final.pdf/download

**Comment by kibojoe** [comment]
hi,
password for unlock screen is **kibojoe**
i'll put this information in the guide...

vlw fwi, Holmes :)
