### ISSUE TITLE
Htop is not started

### ISSUE THREAD

**Issue by ghost** [kibojoe/build-iso#5]
Htop is not launched from starting menu, but launched through a terminal

**Comment by kibojoe** [comment]
hello @plohoyav 
any problem with sakura
i did tests with other terminals and it worked
to solve with sakura do this
open **htop.desktop** in **/usr/share/applications** (open with root)
then find the line that reads:

**Terminal=true**

and change it to read:

**Terminal=false**

then find the line that reads:

**Exec=htop**

and change this to read:

**Exec=sakura -e htop**

and refresh JWM with **Mod4+u**

vlw fwi, Holmes :)

**Comment by ghost** [comment]
OK, thank you

**Comment by kibojoe** [comment]
change **htop.desktop** and locked update!

vlw fwi, Holmes :)

**Comment by kibojoe** [comment]
closed!

vlw fwi, Holmes :)
