### ISSUE TITLE
cfgroup: cfgroup2: unknown option "nsdelegate"

### ISSUE THREAD

**Issue by ghost** [kibojoe/build-iso#6]
This message i see when booting linux.
Probably this need to fix.

**Comment by kibojoe** [comment]
hi,
i'll see this
i made a new iso and got the same message...

vlw fwi, Holmes :)

**Comment by kibojoe** [comment]
i did some research and apparently it's a kernel problem
i believe that it should soon be corrected...

vlw fwi, Holmes :)

**Comment by kibojoe** [comment]
more informations

https://forum.manjaro.org/t/cant-log-into-manjaro-cgroup-cgroup2-unknown-option-nsdelegate/33494/50

and

https://forum.manjaro.org/t/cant-log-into-manjaro-cgroup-cgroup2-unknown-option-nsdelegate/33494/54

i'm going to change the kernel to 414...

vlw fwi, Holmes :)

**Comment by kibojoe** [comment]
closed!

vlw fwi, Holmes :)
