### ISSUE TITLE
The installer requires 1 GB of RAM

### ISSUE THREAD

**Issue by ghost** [kibojoe/build-iso#7]
Is it possible to decrease requirements?

**Comment by kibojoe** [comment]
hello,
test it with you: open editor in live-session and edit `/etc/calamares/modules/welcome.conf` and `/usr/share/calamares/modules/welcome.conf`. edit

**requiredRam:    1.0**

change **1.0** for **0.5**. 

vlw fwi, Holmes :)

**Comment by ghost** [comment]
Thank you

**Comment by kibojoe** [comment]
closed!

vlw fwi, Holmes :)
