### ISSUE TITLE
nvidia driver is already registered

### ISSUE THREAD

**Issue by ghost** [kibojoe/build-iso#8]
i installed kibojoe 17.09rc5, run sudo /usr/bin/kibojoe/kdusm, install nonfree drivers (nvidia), rebooted and cannot boot. 

while booting the same report recurs with an interval 5 seconds.
system does not run.

here https://bbs.archlinux.org/viewtopic.php?id=222142 say that i need kernel <=4.8 or nouveau

i booted from another partition and used mhwd-chroot to install nouveau (free driver)

**Comment by plohoyav** [comment]
i booted from another partition and used mhwd-chroot to install nouveau

**Comment by kibojoe** [comment]
hello,
and now?
it's OK?

vlw fwi, Holmes :)

**Comment by ghost** [comment]
May be you can add installation of kernel 4.8 when installer of kdusm installs nvidia driver.
Or some warning of user.

**Comment by kibojoe** [comment]
closed!

vlw fwi, Holmes :)
