### ISSUE TITLE
Some errors in journalctl

### ISSUE THREAD

**Issue by ghost** [kibojoe/build-iso#9]
running sudo journalctl outputs:

-- Logs begin at Mon 2017-11-06 18:33:31 MSK, end at Thu 2017-11-09 11:43:02 MSK. --
ноя 06 18:33:31 user-pc kernel: ACPI BIOS Warning (bug): Optional FADT field Pm2ControlBlock has valid Length but zero Address: 0x0000000000000000/0x1 (20170728/tbfadt-658)
ноя 06 18:33:31 user-pc kernel: mtrr: your CPUs had inconsistent variable MTRR settings
ноя 06 18:33:31 user-pc kernel: ACPI Exception: Could not find/resolve named package element: \_PR_.CPU0 (20170728/dspkginit-381)
ноя 06 18:33:31 user-pc kernel: ACPI: PCI Interrupt Link [APCF] enabled at IRQ 22
ноя 06 18:33:31 user-pc kernel: ACPI: PCI Interrupt Link [APCL] enabled at IRQ 21
ноя 06 18:33:31 user-pc kernel: Warning! ehci_hcd should always be loaded before uhci_hcd and ohci_hcd, not after
ноя 06 18:33:31 user-pc kernel: ACPI: PCI Interrupt Link [APSI] enabled at IRQ 23
ноя 06 18:33:31 user-pc kernel: ACPI: PCI Interrupt Link [APSJ] enabled at IRQ 23
ноя 06 18:33:31 user-pc systemd-journald[171]: Journal started
ноя 06 18:33:31 user-pc systemd-journald[171]: Runtime journal (/run/log/journal/30caaecca5eb41df9ab2ef3f793ccd76) is 8.0M, max 87.5M, 79.5M free.
ноя 06 18:33:31 user-pc systemd-journald[171]: Time spent on flushing to /var is 6.268ms for 10 entries.
ноя 06 18:33:31 user-pc systemd-journald[171]: System journal (/var/log/journal/30caaecca5eb41df9ab2ef3f793ccd76) is 8.0M, max 250.0M, 242.0M free.
ноя 06 18:33:32 user-pc kernel: ACPI: Invalid passive threshold
ноя 06 18:33:32 user-pc kernel: (NULL device *): hwmon_device_register() is deprecated. Please convert the driver to use hwmon_device_register_with_info().
ноя 06 18:33:32 user-pc kernel: ACPI: PCI Interrupt Link [AAZA] enabled at IRQ 20
ноя 06 18:33:32 user-pc kernel: ACPI: PCI Interrupt Link [APCH] enabled at IRQ 22
ноя 06 18:33:41 user-pc systemd-udevd[185]: Process '/usr/bin/alsactl restore 0' failed with exit code 99.
ноя 06 18:33:44 user-pc ntpd[451]: bind(21) AF_INET6 fe80::1a3:8677:7df7:c624%2#123 flags 0x11 failed: Cannot assign requested address
ноя 06 18:33:44 user-pc ntpd[451]: unable to create socket on enp0s7 (5) for fe80::1a3:8677:7df7:c624%2#123
ноя 06 18:33:44 user-pc kernel: ACPI: PCI Interrupt Link [AIGP] enabled at IRQ 21
ноя 06 18:33:44 user-pc kernel: nouveau 0000:00:0d.0: DRM: DCB type 4 not known
ноя 06 18:33:44 user-pc kernel: nouveau 0000:00:0d.0: DRM: Unknown-1 has no encoders, removing
ноя 06 18:33:49 user-pc systemd[1]: lxdm.service: Failed with result 'exit-code'.
ноя 06 18:51:34 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:51:34 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:51:34 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:51:34 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:51:35 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:51:35 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:51:35 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:51:35 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:51:49 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0100024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:52:17 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:56:20 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:56:20 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:56:20 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:56:20 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:56:20 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:56:20 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:56:21 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:56:21 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:56:21 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:56:21 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
ноя 06 18:57:00 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0200024
ноя 06 18:57:00 user-pc kernel: nouveau 0000:00:0d.0: gr: intr 00100000 [ERROR] nsource 00000002 [DATA_ERROR] nstatus 02000000 [BAD_ARGUMENT] ch 1 [00048000 Xorg[468]] subc 7 class 4497 mthd 0208 data 0400024
lines 1-61

**Comment by ghost** [comment]
For last 2 boots sudo journalctl output was:

-- Reboot --
ноя 10 20:31:48 user-pc kernel: ACPI BIOS Warning (bug): Optional FADT field Pm2ControlBlock has valid Length but zero Address: 0x0000000000000000/0x1 (20170728/tbfadt-658)
ноя 10 20:31:48 user-pc kernel: mtrr: your CPUs had inconsistent variable MTRR settings
ноя 10 20:31:48 user-pc kernel: ACPI Exception: Could not find/resolve named package element: \_PR_.CPU0 (20170728/dspkginit-381)
ноя 10 20:31:48 user-pc kernel: ACPI: PCI Interrupt Link [APCF] enabled at IRQ 22
ноя 10 20:31:48 user-pc kernel: ACPI: PCI Interrupt Link [APCL] enabled at IRQ 21
ноя 10 20:31:48 user-pc kernel: bootsplash: Failed to read file: /bootsplash.55559
ноя 10 20:31:48 user-pc kernel: bootsplash: Failed to initialize.
ноя 10 20:31:48 user-pc kernel: Warning! ehci_hcd should always be loaded before uhci_hcd and ohci_hcd, not after
ноя 10 20:31:48 user-pc kernel: ACPI: PCI Interrupt Link [APSI] enabled at IRQ 23
ноя 10 20:31:48 user-pc kernel: ACPI: PCI Interrupt Link [APSJ] enabled at IRQ 23
ноя 10 20:31:48 user-pc systemd-journald[170]: Journal started
ноя 10 20:31:48 user-pc systemd-journald[170]: Runtime journal (/run/log/journal/30caaecca5eb41df9ab2ef3f793ccd76) is 8.0M, max 87.5M, 79.5M free.
ноя 10 20:31:48 user-pc systemd-journald[170]: Time spent on flushing to /var is 73.665ms for 12 entries.
ноя 10 20:31:48 user-pc systemd-journald[170]: System journal (/var/log/journal/30caaecca5eb41df9ab2ef3f793ccd76) is 16.0M, max 250.0M, 233.9M free.
ноя 10 20:31:51 user-pc kernel: ACPI: Invalid passive threshold
ноя 10 20:31:51 user-pc kernel: (NULL device *): hwmon_device_register() is deprecated. Please convert the driver to use hwmon_device_register_with_info().
ноя 10 20:31:51 user-pc kernel: ACPI: PCI Interrupt Link [APCH] enabled at IRQ 20
ноя 10 20:31:51 user-pc kernel: ACPI: PCI Interrupt Link [AAZA] enabled at IRQ 22
ноя 10 20:31:55 user-pc ntpd[346]: bind(21) AF_INET6 fe80::1a3:8677:7df7:c624%2#123 flags 0x11 failed: Cannot assign requested address
ноя 10 20:31:55 user-pc ntpd[346]: unable to create socket on enp0s7 (5) for fe80::1a3:8677:7df7:c624%2#123
ноя 10 20:31:56 user-pc kernel: ACPI: PCI Interrupt Link [AIGP] enabled at IRQ 21
ноя 10 20:31:56 user-pc kernel: nouveau 0000:00:0d.0: DRM: DCB type 4 not known
ноя 10 20:31:56 user-pc kernel: nouveau 0000:00:0d.0: DRM: Unknown-1 has no encoders, removing
ноя 10 20:31:56 user-pc kernel: bootsplash: Failed to read file: /bootsplash.55559
ноя 10 20:31:56 user-pc kernel: bootsplash: Failed to initialize.
ноя 10 20:32:00 user-pc kernel: nouveau 0000:00:0d.0: bus: MMIO write of 00720001 FAULT at 00b000
ноя 10 21:45:46 user-pc systemd[832]: dunst.service: Failed with result 'exit-code'.
ноя 10 21:45:50 user-pc kernel: systemd-shutdow: 27 output lines suppressed due to ratelimiting
ноя 10 21:45:50 user-pc systemd-journald[170]: Journal stopped
-- Reboot --
ноя 11 08:07:27 user-pc kernel: ACPI BIOS Warning (bug): Optional FADT field Pm2ControlBlock has valid Length but zero Address: 0x0000000000000000/0x1 (20170728/tbfadt-658)
ноя 11 08:07:27 user-pc kernel: mtrr: your CPUs had inconsistent variable MTRR settings
ноя 11 08:07:27 user-pc kernel: ACPI Exception: Could not find/resolve named package element: \_PR_.CPU0 (20170728/dspkginit-381)
ноя 11 08:07:27 user-pc kernel: ACPI: PCI Interrupt Link [APCF] enabled at IRQ 22
ноя 11 08:07:27 user-pc kernel: ACPI: PCI Interrupt Link [APCL] enabled at IRQ 21
ноя 11 08:07:27 user-pc kernel: bootsplash: Failed to read file: /bootsplash.55559
ноя 11 08:07:27 user-pc kernel: bootsplash: Failed to initialize.
ноя 11 08:07:27 user-pc kernel: Warning! ehci_hcd should always be loaded before uhci_hcd and ohci_hcd, not after
ноя 11 08:07:27 user-pc kernel: ACPI: PCI Interrupt Link [APSI] enabled at IRQ 23
ноя 11 08:07:27 user-pc kernel: ACPI: PCI Interrupt Link [APSJ] enabled at IRQ 23
ноя 11 08:07:27 user-pc systemd-journald[164]: Journal started
ноя 11 08:07:27 user-pc systemd-journald[164]: Runtime journal (/run/log/journal/30caaecca5eb41df9ab2ef3f793ccd76) is 8.0M, max 87.5M, 79.5M free.
ноя 11 08:07:27 user-pc systemd-journald[164]: Time spent on flushing to /var is 59.503ms for 12 entries.
ноя 11 08:07:27 user-pc systemd-journald[164]: System journal (/var/log/journal/30caaecca5eb41df9ab2ef3f793ccd76) is 16.0M, max 250.0M, 233.9M free.
ноя 11 08:07:30 user-pc kernel: ACPI: Invalid passive threshold
ноя 11 08:07:30 user-pc kernel: (NULL device *): hwmon_device_register() is deprecated. Please convert the driver to use hwmon_device_register_with_info().
ноя 11 08:07:30 user-pc kernel: ACPI: PCI Interrupt Link [APCH] enabled at IRQ 20
ноя 11 08:07:30 user-pc kernel: ACPI: PCI Interrupt Link [AAZA] enabled at IRQ 22
ноя 11 08:07:31 user-pc kernel: ACPI: PCI Interrupt Link [AIGP] enabled at IRQ 21
ноя 11 08:07:31 user-pc kernel: nouveau 0000:00:0d.0: DRM: DCB type 4 not known
ноя 11 08:07:31 user-pc kernel: nouveau 0000:00:0d.0: DRM: Unknown-1 has no encoders, removing
ноя 11 08:07:31 user-pc kernel: bootsplash: Failed to read file: /bootsplash.55559
ноя 11 08:07:31 user-pc kernel: bootsplash: Failed to initialize.
ноя 11 08:07:32 user-pc systemd[1]: logrotate.service: Failed with result 'exit-code'.
ноя 11 08:07:32 user-pc systemd[1]: Failed to start Rotate log files.
ноя 11 08:07:38 user-pc kernel: nouveau 0000:00:0d.0: bus: MMIO write of 00720001 FAULT at 00b000
ноя 11 08:07:43 user-pc ntpd[875]: bind(21) AF_INET6 fe80::1a3:8677:7df7:c624%2#123 flags 0x11 failed: Cannot assign requested address
ноя 11 08:07:43 user-pc ntpd[875]: unable to create socket on enp0s7 (5) for fe80::1a3:8677:7df7:c624%2#123

**Comment by kibojoe** [comment]
hello,
and now?
it's OK?

vlw fwi, Holmes :)

**Comment by ghost** [comment]
@All works fine, but messages are still here :)

-- Reboot --
ноя 11 20:58:21 user-pc kernel: ACPI BIOS Warning (bug): Optional FADT field Pm2ControlBlock has valid Length but zero Address: 0x0000000000000000/0x1 (20170728/tbfadt-658)
ноя 11 20:58:21 user-pc kernel: mtrr: your CPUs had inconsistent variable MTRR settings
ноя 11 20:58:21 user-pc kernel: ACPI Exception: Could not find/resolve named package element: \_PR_.CPU0 (20170728/dspkginit-381)
ноя 11 20:58:21 user-pc kernel: bootsplash: Failed to read file: /bootsplash.55559
ноя 11 20:58:21 user-pc kernel: bootsplash: Failed to initialize.
ноя 11 20:58:21 user-pc kernel: Warning! ehci_hcd should always be loaded before uhci_hcd and ohci_hcd, not after
ноя 11 20:58:21 user-pc kernel: ACPI: Invalid passive threshold
ноя 11 20:58:21 user-pc kernel: (NULL device *): hwmon_device_register() is deprecated. Please convert the driver to use hwmon_device_register_with_info().
ноя 11 20:58:27 user-pc ntpd[394]: bind(21) AF_INET6 fe80::1a3:8677:7df7:c624%2#123 flags 0x11 failed: Cannot assign requested address
ноя 11 20:58:27 user-pc ntpd[394]: unable to create socket on enp0s7 (5) for fe80::1a3:8677:7df7:c624%2#123
ноя 11 20:58:28 user-pc kernel: nouveau 0000:00:0d.0: DRM: DCB type 4 not known
ноя 11 20:58:28 user-pc kernel: nouveau 0000:00:0d.0: DRM: Unknown-1 has no encoders, removing
ноя 11 20:58:28 user-pc kernel: bootsplash: Failed to read file: /bootsplash.55559
ноя 11 20:58:28 user-pc kernel: bootsplash: Failed to initialize.
ноя 11 20:58:33 user-pc kernel: nouveau 0000:00:0d.0: bus: MMIO write of 00720001 FAULT at 00b000

**Comment by kibojoe** [comment]
see this

https://forum.manjaro.org/t/unstable-update-2017-10-27-kde-gnome-deepin-firefox-mesa/33561/6

vlw fwi, Holmes :)

**Comment by kibojoe** [comment]
closed!

vlw fwi, Holmes :)
